- src/main/java/org/springeel/oneclickrecipe/sample/service/impl/TestServiceImpl.java
- 
- 예시 코드 수정
- Mapper 분리 (dto, entity)
- Mapper 빈 등록
-
> Sample - 예시 코드 수정

- src/main/java/org/springeel/oneclickrecipe/global/exception/CustomException.java
- src/main/java/org/springeel/oneclickrecipe/global/exception/ErrorCode.java
- src/main/java/org/springeel/oneclickrecipe/global/exception/handler/GlobalExceptionHandler.java
- src/main/java/org/springeel/oneclickrecipe/sample/controller/TestController.java
- src/main/java/org/springeel/oneclickrecipe/sample/exception/AlreadyExistsTestException.java
- src/main/java/org/springeel/oneclickrecipe/sample/exception/ForbiddenAccessTestException.java
- src/main/java/org/springeel/oneclickrecipe/sample/exception/NotFoundTestException.java
- src/main/java/org/springeel/oneclickrecipe/sample/exception/TestErrorCode.java
- src/main/java/org/springeel/oneclickrecipe/sample/service/impl/TestServiceImpl.java
- close #19 
- 커스텀 예외 처리 규격 설정
- 각 도메인별로 CustomException 클래스를 상속받는 커스텀 예외를 생성
- 각 도메인별로 ErrorCode 인터페이스를 구현하는 에러 메세지 생성
- ErrorCode 인터페이스를 구현한 enum을 생성하는 방식
-
> Feature/custom exception - 커스텀 예외 처리 규격 설정

- src/main/java/org/springeel/oneclickrecipe/domain/user/entity/UserRole.java
> Feat: UserRole, Authority 추가

- src/main/java/org/springeel/oneclickrecipe/global/config/WebSecurityConfig.java
- 시큐리티 설정
- jwt 인가 필터 추가
- 로그인, 회원가입 API 설정
- WebSecurityConfig
- JwtAuthorizationFilter
-
> [#18]Feat: Spring Security 설정

- src/main/java/org/springeel/oneclickrecipe/domain/user/mapper/entity/UserEntityMapper.java
> Feature/user mapper - User @Mapping 수정

- src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/controller/RecipeProcessController.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/dto/controller/RecipeProcessCreateControllerRequestDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/dto/service/RecipeProcessCreateServiceRequestDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/entity/RecipeProcess.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/exception/AlreadyExistsRecipeProcessException.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/exception/ForbiddenAccessRecipeProcessException.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/exception/NotFoundRecipeProcessException.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/exception/RecipeProcessErrorCode.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/mapper/dto/RecipeProcessDtoMapper.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/mapper/entity/RecipeProcessEntityMapper.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/repository/RecipeProcessRepository.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/service/RecipeProcessService.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/service/impl/RecipeProcessServiceImpl.java
- close #57 
- 조리과정 삭제기능을 구현하였습니다.
-
> Feature/recipeprocess delete 레시피_조리과정 삭제 기능 추가

- build.gradle
- src/main/java/org/springeel/oneclickrecipe/domain/user/dto/controller/UserSignUpControllerRequestDto.java
- src/main/java/org/springeel/oneclickrecipe/global/config/SwaggerConfig.java
- 
- 회원가입 Bean validation
- 이메일 형식
- 닉네임 길이 제한
- 비밀번호 최소 8자 이상
-
> Feature/signup validation - 회원가입 Bean validation

- src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/controller/RecipeProcessController.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/dto/controller/RecipeProcessUpdateControllerRequestDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/dto/service/RecipeProcessUpdateServiceRequestDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/entity/RecipeProcess.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/mapper/dto/RecipeProcessDtoMapper.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/service/RecipeProcessService.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/service/impl/RecipeProcessServiceImpl.java
- close #59 
- 조리과정 수정을 위한 기능 추가
-
> Feature/recipeprocess update 레시피_조리과정 업데이트 기능 구현

- src/main/java/org/springeel/oneclickrecipe/domain/recipe/controller/RecipeController.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipe/dto/controller/RecipeDeleteControllerRequestDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipe/dto/service/RecipeDeleteServiceRequestDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipe/mapper/dto/RecipeDtoMapper.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipe/service/RecipeService.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipe/service/impl/RecipeServiceImpl.java
- close #63 
- 레시피 삭제 기능 코드 리팩토링 하였습니다.
-
> Refactor: 레시피 삭제 기능 코드 리팩토링

- src/main/java/org/springeel/oneclickrecipe/domain/review/controller/ReviewController.java
- src/main/java/org/springeel/oneclickrecipe/domain/review/dto/controller/ReviewDeleteControllerRequestDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/review/dto/service/ReviewDeleteServiceRequestDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/review/mapper/dto/ReviewDtoMapper.java
- src/main/java/org/springeel/oneclickrecipe/domain/review/mapper/entity/ReviewEntityMapper.java
- src/main/java/org/springeel/oneclickrecipe/domain/review/service/ReviewService.java
- src/main/java/org/springeel/oneclickrecipe/domain/review/service/impl/ReviewServiceImpl.java
- close #50 
-후기 삭제 기능 구현 & 후기 수정 기능 수정 
-
> Feature/review delete - 후기 삭제 기능 구현 & 후기 수정 기능 수정

- src/main/java/org/springeel/oneclickrecipe/global/config/WebSecurityConfig.java
> Feature/cors - CORS 설정

- src/main/java/org/springeel/oneclickrecipe/domain/recipelike/controller/RecipeLikeController.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipelike/exception/RecipeLikeErrorCode.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipelike/repository/RecipeLikeRepository.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipelike/service/RecipeLikeService.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipelike/service/impl/RecipeLikeServiceImpl.java
- close #94 
- 좋아요 삭제 기능을 구현하였습니다.
-
> Feature/like/delete 좋아요 삭제 기능

- src/main/java/org/springeel/oneclickrecipe/global/util/S3Provider.java
- close #98 
- S3에 저장된 파일 삭제 구현
-
> feature: S3에 저장된 파일 삭제 기능 구현

- .gitignore
- src/main/java/org/springeel/oneclickrecipe/domain/order/entity/Order.java
- src/main/java/org/springeel/oneclickrecipe/domain/payment/controller/PaymentController.java
- src/main/java/org/springeel/oneclickrecipe/domain/payment/dto/controller/KakaoPayApprovalControllerRequestDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/payment/dto/controller/KakaoPayReadyControllerRequestDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/payment/dto/kakaopay/Amount.java
- src/main/java/org/springeel/oneclickrecipe/domain/payment/dto/kakaopay/KakaoPayApprovalResponseDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/payment/dto/kakaopay/KakaoPayReadyResponseDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/payment/dto/service/KakaoPayApprovalServiceRequestDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/payment/dto/service/KakaoPayReadyServiceRequestDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/payment/mapper/dto/PaymentDtoMapper.java
- src/main/java/org/springeel/oneclickrecipe/domain/payment/repository/PaymentRepository.java
- src/main/java/org/springeel/oneclickrecipe/domain/payment/service/PaymentService.java
- src/main/java/org/springeel/oneclickrecipe/domain/payment/service/impl/PaymentServiceImpl.java
- src/main/java/org/springeel/oneclickrecipe/global/config/RestTemplateConfig.java
- src/main/java/org/springeel/oneclickrecipe/global/config/WebSecurityConfig.java
- src/test/java/org/springeel/oneclickrecipe/domain/order/service/impl/OrderServiceImplTest.java
> Test/order - OrderService 테스트 코드 예시

- src/main/java/org/springeel/oneclickrecipe/domain/order/entity/Order.java
- src/main/java/org/springeel/oneclickrecipe/domain/payment/controller/PaymentController.java
- src/main/java/org/springeel/oneclickrecipe/domain/payment/dto/controller/KakaoPayApprovalControllerRequestDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/payment/dto/controller/KakaoPayReadyControllerRequestDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/payment/dto/kakaopay/Amount.java
- src/main/java/org/springeel/oneclickrecipe/domain/payment/dto/kakaopay/KakaoPayApprovalResponseDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/payment/dto/kakaopay/KakaoPayReadyResponseDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/payment/dto/service/KakaoPayApprovalServiceRequestDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/payment/dto/service/KakaoPayReadyServiceRequestDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/payment/mapper/dto/PaymentDtoMapper.java
- src/main/java/org/springeel/oneclickrecipe/domain/payment/repository/PaymentRepository.java
- src/main/java/org/springeel/oneclickrecipe/domain/payment/service/PaymentService.java
- src/main/java/org/springeel/oneclickrecipe/domain/payment/service/impl/PaymentServiceImpl.java
- src/main/java/org/springeel/oneclickrecipe/global/config/RestTemplateConfig.java
- src/main/java/org/springeel/oneclickrecipe/global/config/WebSecurityConfig.java
- close #89 
- 카카오페이 결제 연동
- 결제 성공 시, OrderStatus를 WAITING에서 APPROVEMENT로 변경
- CORS 헤더 설정
-
> Feature/kakaopay - 카카오페이 결제 연동

- src/main/java/org/springeel/oneclickrecipe/domain/cart/controller/CartController.java
- src/main/java/org/springeel/oneclickrecipe/domain/cart/dto/controller/CartAddControllerRequestDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/cart/dto/service/CartAddServiceRequestDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/cart/mapper/dto/CartDtoMapper.java
- src/main/java/org/springeel/oneclickrecipe/domain/cart/repository/CartRepository.java
- src/main/java/org/springeel/oneclickrecipe/domain/cart/service/CartService.java
- src/main/java/org/springeel/oneclickrecipe/domain/cart/service/impl/CartServiceImpl.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipefood/repository/RecipeFoodRepository.java
- close #97 
- 장바구니 아이템 추가 기능 구현 
-
> Feature/cart/create - 장바구니 아이템 추가 기능 구현 

- .gitignore
- src/main/java/org/springeel/oneclickrecipe/domain/payment/service/impl/PaymentServiceImpl.java
- src/main/java/org/springeel/oneclickrecipe/domain/user/controller/UserController.java
- src/main/java/org/springeel/oneclickrecipe/global/config/WebSecurityConfig.java
- UserController에서 Bean Validation 적용
- Spring Security에서 recipes와 reviews 조회 API에 대해서는 누구나 조회할 수 있게 설정
-
> Feature/security - Bean Validation & Security 인가 설정

- src/main/java/org/springeel/oneclickrecipe/global/config/WebSecurityConfig.java
- 
- /api/v1/recipes/{recipeId}/reviews 인가 작업 추가
-
> feat/security - /api/v1/recipes/{recipeId}/reviews 인가 작업 추가

- src/main/java/org/springeel/oneclickrecipe/global/exception/dto/BeanValidationExceptionResponseDto.java
- src/main/java/org/springeel/oneclickrecipe/global/exception/dto/FieldErrorResponseDto.java
- src/main/java/org/springeel/oneclickrecipe/global/exception/handler/GlobalExceptionHandler.java
- close #125 
- Bean Validation으로 발생하는 예외 처리 기능 추가
- DTO 생성 및 반환 작업
-
> [#125]Feat: Bean Validation handler 추가

- src/main/java/org/springeel/oneclickrecipe/domain/cart/service/impl/CartServiceImpl.java
> Refactor: cart 수정

- src/main/java/org/springeel/oneclickrecipe/domain/orderdetail/entity/OrderDetail.java
- src/main/java/org/springeel/oneclickrecipe/domain/orderdetail/mapper/entity/OrderDetailEntityMapper.java
- src/main/java/org/springeel/oneclickrecipe/domain/payment/service/impl/PaymentServiceImpl.java
> Feature/orderdetail/unit - OrderDetail unit 필드 추가

- .github/workflows/cd.yml
- .github/workflows/ci.yml
> Chore: 경로 확인 테스트

- .github/workflows/ci.yml
- .github/workflows/cicd.yml
> Chore: CI/CD workflows 설정

- src/main/java/org/springeel/oneclickrecipe/domain/follow/entity/Follow.java
- src/main/java/org/springeel/oneclickrecipe/domain/follow/entity/FollowId.java
> Refactor: Subscrive -> Follow 명칭 변경

- .github/workflows/cicd.yml
> Chore: 로그 출력 파일 추가 nohup_log.out

- src/test/java/org/springeel/oneclickrecipe/domain/order/service/OrderServiceCreateTest.java
- close #130 
- Test: 장바구니 아이템 조회 테스트
-
> Test: 장바구니 아이템 조회 테스트

- src/test/java/org/springeel/oneclickrecipe/domain/order/service/OrderServiceCreateTest.java
- close #172 
- 주문 파트 테스트 코드 작성
-
> Test - 주문 파트 테스트 코드 작성

- .gitignore
- src/test/java/org/springeel/oneclickrecipe/OneClickRecipeApplicationTest.java
- src/test/resources/application.yml
> feature/order/refactor - CI 확인용 커밋

- src/main/java/org/springeel/oneclickrecipe/domain/admin/controller/AdminController.java
- src/main/java/org/springeel/oneclickrecipe/domain/admin/dto/AdminUserResponseDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/admin/dto/UserRoleUpdateRequestDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/admin/service/AdminService.java
- src/main/java/org/springeel/oneclickrecipe/domain/admin/service/impl/AdminServiceImpl.java
- src/main/java/org/springeel/oneclickrecipe/domain/user/entity/User.java
- src/main/java/org/springeel/oneclickrecipe/global/config/WebSecurityConfig.java
> Feature/admin - 관리자 기능 구현

- src/main/java/org/springeel/oneclickrecipe/domain/review/dto/service/response/ReviewReadResponseDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/review/mapper/entity/ReviewEntityMapper.java
- 리뷰 작성 시 데이터 조회할 때 작성자도 함께 표기
-
-
> feature: review 작성자 닉네임 추가

- src/main/java/org/springeel/oneclickrecipe/domain/recipelike/controller/RecipeLikeController.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipelike/repository/RecipeLikeRepository.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipelike/service/RecipeLikeService.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipelike/service/impl/RecipeLikeServiceImpl.java
- close #193 
- 좋아요 조회 기능 구현
-
> Feature/like/read - 좋아요 조회 기능 구현

- src/main/java/org/springeel/oneclickrecipe/domain/recipe/dto/service/response/RecipeAllReadResponseDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/user/controller/KakaoController.java
- src/main/java/org/springeel/oneclickrecipe/domain/user/controller/UserController.java
- src/main/java/org/springeel/oneclickrecipe/domain/user/dto/service/request/UserLoginServiceRequestDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/user/dto/service/request/UserSignUpServiceRequestDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/user/dto/service/response/UserLoginResponseDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/user/mapper/dto/UserDtoMapper.java
- src/main/java/org/springeel/oneclickrecipe/domain/user/mapper/entity/UserEntityMapper.java
- src/main/java/org/springeel/oneclickrecipe/domain/user/service/KakaoService.java
- src/main/java/org/springeel/oneclickrecipe/domain/user/service/UserService.java
- src/main/java/org/springeel/oneclickrecipe/domain/user/service/impl/UserServiceImpl.java
- 
- 로그인, 카카오 로그인, 토큰 재발급 API 호출 시, LoginDto 반환
-
> Feature/user/refresh - 로그인, 카카오 로그인, 토큰 재발급 API 호출 시, LoginDto 반환

- build.gradle
- src/main/java/org/springeel/oneclickrecipe/domain/order/service/impl/OrderServiceImpl.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipe/controller/RecipeController.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipefood/dto/controller/RecipeFoodCreateControllerRequestDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/dto/controller/RecipeProcessCreateControllerRequestDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/review/entity/Review.java
> Feature/validation/all - Bean Validation 설정 및 OrderDetail 가격 수정

- src/main/java/org/springeel/oneclickrecipe/domain/review/service/impl/ReviewServiceImpl.java
- 
- 레시피 작성자도 리뷰 삭제 가능 하도록 로직 수정
-
> refactor: 로직 변경 및 변수명 수정

- src/main/java/org/springeel/oneclickrecipe/domain/review/controller/ReviewController.java
- src/main/java/org/springeel/oneclickrecipe/domain/review/dto/service/response/ReviewCreateResponseDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/review/mapper/entity/ReviewEntityMapper.java
- src/main/java/org/springeel/oneclickrecipe/domain/review/service/ReviewService.java
- src/main/java/org/springeel/oneclickrecipe/domain/review/service/impl/ReviewServiceImpl.java
> Feat: Review 생성 DTO 추가

- src/main/java/org/springeel/oneclickrecipe/domain/recipe/controller/RecipeController.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipe/service/RecipeService.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipe/service/impl/RecipeServiceImpl.java
> Feat: Recipe 목록 조회 시, 좋아요 여부 확인

- src/main/java/org/springeel/oneclickrecipe/domain/recipe/controller/RecipeController.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipe/repository/RecipeRepository.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipe/service/RecipeService.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipe/service/impl/RecipeServiceImpl.java
- src/main/java/org/springeel/oneclickrecipe/sample/controller/TestController.java
- src/main/java/org/springeel/oneclickrecipe/sample/repository/TestRepository.java
- src/main/java/org/springeel/oneclickrecipe/sample/service/TestService.java
- src/main/java/org/springeel/oneclickrecipe/sample/service/impl/TestServiceImpl.java
> Feat: 무한 스크롤 레시피 조회용 Slice 추가

- src/main/java/org/springeel/oneclickrecipe/domain/recipe/controller/RecipeController.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipe/dto/service/response/RecipeReadResponseDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipe/service/RecipeService.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipe/service/impl/RecipeServiceImpl.java
- 
- 구독 기능을 레시피 단건조회에서 수행하기 위한 리팩토링
> refactor: 구독 기능을 레시피 단건조회에서 수행하기 위한 리팩토링

- src/main/java/org/springeel/oneclickrecipe/domain/recipe/service/impl/RecipeServiceImpl.java
> refactor: intro 추가

- src/main/java/org/springeel/oneclickrecipe/domain/recipe/controller/RecipeController.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipe/service/impl/RecipeServiceImpl.java
- src/main/java/org/springeel/oneclickrecipe/domain/review/controller/ReviewController.java
- src/main/java/org/springeel/oneclickrecipe/domain/review/repository/ReviewRepository.java
- src/main/java/org/springeel/oneclickrecipe/domain/review/service/ReviewService.java
- src/main/java/org/springeel/oneclickrecipe/domain/review/service/impl/ReviewServiceImpl.java
> Feat: 리뷰 조회할 때, 무한 스크롤 적용

- src/main/java/org/springeel/oneclickrecipe/domain/user/dto/controller/PasswordUpdateControllerRequestDto.java
> Refactor: 비밀번호 길이조건수정

- src/main/java/org/springeel/oneclickrecipe/domain/recipe/controller/RecipeController.java
> refactor: RecipeController update 기능

- src/main/java/org/springeel/oneclickrecipe/domain/recipefood/dto/service/response/RecipeFoodReadResponseDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipefood/service/impl/RecipeFoodServiceImpl.java
> refactor: 레피시식재료 조회 변수명 변경

- src/main/java/org/springeel/oneclickrecipe/domain/cart/entity/Cart.java
- src/main/java/org/springeel/oneclickrecipe/domain/follow/entity/Follow.java
- src/main/java/org/springeel/oneclickrecipe/domain/order/entity/Order.java
- src/main/java/org/springeel/oneclickrecipe/domain/payment/entity/Payment.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipe/entity/Recipe.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipelike/entity/RecipeLike.java
- src/main/java/org/springeel/oneclickrecipe/domain/review/entity/Review.java
- src/main/java/org/springeel/oneclickrecipe/domain/user/controller/UserController.java
- src/main/java/org/springeel/oneclickrecipe/domain/user/dto/controller/DeleteUserControllerRequestDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/user/dto/service/request/DeleteUserServiceRequestDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/user/mapper/dto/UserDtoMapper.java
- src/main/java/org/springeel/oneclickrecipe/domain/user/mapper/entity/UserEntityMapper.java
- src/main/java/org/springeel/oneclickrecipe/domain/user/service/UserService.java
- src/main/java/org/springeel/oneclickrecipe/domain/user/service/impl/UserServiceImpl.java
> Feature/user/delete - 회원탈퇴기능

- src/main/java/org/springeel/oneclickrecipe/domain/recipe/controller/RecipeController.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipe/dto/controller/RecipeUpdateControllerRequestDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipe/dto/service/request/RecipeUpdateServiceRequestDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipe/service/impl/RecipeServiceImpl.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/controller/RecipeProcessController.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/dto/controller/RecipeProcessUpdateControllerRequestDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/dto/service/request/RecipeProcessUpdateServiceRequestDto.java
- src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/service/impl/RecipeProcessServiceImpl.java
- 
- 이미지 업데이트를 하기 위한 검증 로직 추가
-
> feature: 이미지 수정을 결정하기 위한 검증 로직 추가

- src/main/java/org/springeel/oneclickrecipe/domain/order/controller/OrderController.java
- src/main/java/org/springeel/oneclickrecipe/domain/order/repository/OrderRepository.java
- src/main/java/org/springeel/oneclickrecipe/domain/order/service/OrderService.java
- src/main/java/org/springeel/oneclickrecipe/domain/order/service/impl/OrderServiceImpl.java
> Feat: getAllUserOrders 페이지네이션 적용

- src/test/java/org/springeel/oneclickrecipe/domain/review/service/impl/ReviewServiceImplTest.java
- close #228 
- 리뷰조회 테스트코드 작성
-
> Test: 리뷰조회 테스트코드 작성

- src/test/java/org/springeel/oneclickrecipe/domain/review/service/impl/ReviewServiceImplTest.java
> Test/review/create - 리뷰작성 테스트코드 작성

- src/main/java/org/springeel/oneclickrecipe/global/s3/S3Provider.java
- close #234 
- s3 업데이트 로직 수정
-
> refactor: s3 업데이트 로직 수정

- src/test/java/org/springeel/oneclickrecipe/domain/review/service/impl/ReviewServiceImplTest.java
- close #238 
-리뷰수정 테스트코드 작성
-
> Test: 리뷰수정 테스트코드 작성

- .github/workflows/cicd.yml
- Dockerfile
- src/main/java/org/springeel/oneclickrecipe/domain/recipe/mapper/entity/RecipeEntityMapper.java
- src/test/java/org/springeel/oneclickrecipe/domain/review/service/impl/ReviewServiceImplTest.java
> Merge - 배포

- src/test/java/org/springeel/oneclickrecipe/domain/review/service/impl/ReviewServiceImplTest.java
- close #241 
-리뷰삭제 테스트코드 작성
-
> Test: 리뷰삭제 테스트코드 작성

- README.md
> feat - 리드미 수정

- README.md
> feat : 리드미 수정
